### Get parking lot info
GET http://localhost:3001/api/user/parking-lot/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2RjNTdlNTFjMTJkMjVlMzA2NjA5OSIsInVzZXJuYW1lIjoiVGFuIEhvZSBUaGVuZyIsImVtYWlsIjoiamVmZnJleUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYzMzQ1MDA5MCwiZXhwIjoxNjM0NzQ2MDkwfQ.BEv0tUZQ7i3kqwFh18pzsOCoJGwWiQxhhboZv8S4TNk

### Get parking lot info
GET http://localhost:3001/api/user/parking-lot/location
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplZmZyZXkgVGFuIiwiZW1haWwiOiJqZWZmcmV5QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjMxNTI0NDE1LCJleHAiOjE2MzI4MjA0MTV9.3GPQNZDcqwl2qsnrIWhWkJY6QToN57TAEqmIrP5_DZE